name: Azure Node.js Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Copy env file from secrets
        run: echo "${{ secrets.BACKEND_ENV_PRODUCTION }}" > ./backend/.env.production

      - name: Build backend (optional)
        run: npm run build || echo "no build step"
        working-directory: ./backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ghnod-backend         # 새로 만든 App Service 이름
          # publish-profile 제거
          # package 기본값(루트) 사용 시 /backend 지정 필요 없음
          package: ./backend
